### PR TITLE
Implement PiPiper::Bcm2835

### PR DESCRIPTION
**Pull request by elmatou**
offer support for Pin with libbcm2835 1.50
tested for RW methods, need more test on hardware for event support.
should (but not tested) work without sudo for basic GPIO (pull up down excluded)

PWM is on his way with SPI & I2C

### CODE REVIEW

**Comment by zsyed91** [comment]
@elmatou Is this ready to merge? Or do you have anything else you want to add to this PR?

**Comment by elmatou** [comment]
It's good to go for now. 
Pin and PWM work great.
Spi and I2C are implemented as in genuine PiPiper but not tested (as it was). I need to test actual devices to check everything. I suspect I2C & Spi not to have ever worked...
`bin/setup` updates the libbcm2835 with last available tarbal.

**Comment by zsyed91** [comment]
Alright sounds good. Can you squash these commits down to 1. I think it looks good to merge.

**Comment by elmatou** [comment]
Did it

**Comment by zsyed91** [comment]
:+1:

**Pull request merged**
